POST http://localhost:3000/api/users HTTP/1.1
Content-Type: application/json

{
  "firstName":"Tom",
  "lastName":"Musk",
  "email":"elon874@musk.ua",
  "password":"musk4@123",
  "birthday":"1971-06-28",
  "isMale":true
}